import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/ReduxProvider";
import { Toaster } from "@/components/ui/sonner";
import ToastProvider from "@/providers/toaster-provider";
import CheckProvider from "@/providers/check-provider";
import ConfettiProvider from "@/components/providers/confetti-provider";
import dynamic from "next/dynamic";
import Authinitializer from "@/providers/Authinitializer";
const DyanamicStore = dynamic(() => import("@/redux/ReduxProvider"), {
	ssr: false,
	loading: () => <p>Loading ....</p>,
});
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ConfettiProvider />
				<Toaster />
				<ToastProvider />
				{/* {children} */}
				{/* <DyanamicStore>
					<CheckProvider>{children}</CheckProvider>
				</DyanamicStore> */}
				<ReduxProvider>
					{/* <Authinitializer>
					</Authinitializer> */}
					<CheckProvider>{children}</CheckProvider>
				</ReduxProvider>
			</body>
		</html>
	);
}
